### ISSUE TITLE
Flutter 3.13.x Incompatibility

### ISSUE THREAD

**Issue by UlasAkgun** [rodydavis/flutter_pptx#5]
Hi @rodydavis,

The `toUint8List` method of `InputStreamBase` class that is imported from the `archive` package has been updated to accept an optional `Uint8List bytes` method, hence the library is resulting in a build error.

```
Error: The method 'InputFileStream.toUint8List' has fewer positional arguments than those of overridden method 'InputStreamBase.toUint8List'.
  Uint8List toUint8List() {
            ^
```

Also the `screenshot` library version needs to be updated to be able to compile the code as well.

I wanted to prepare a PR for the fix, by updating the `screenshot` library to `2.1.0` and by changing the `toUint8List` method signature to:

```
Uint8List toUint8List([Uint8List? bytes]) {
    // ...
}
```

Yet after the fix, when I try to open the PPTX file I generate using Microsoft Powerpoint, it informs me that the file is corrupted and wants to repair the file. After repairing, the Powerpoint presentation is displayed fine, yet I couldn't figure out what is corrupting the file, hence every generated file requires to be repaired. Not sure if it is resultant from the `toUint8List` change, since this is the first time I am using this package.

Here is a sample code to test the Powerpoint file generation and saving on Flutter Web:

```
import 'package:file_saver/file_saver.dart';
import 'package:flutter/material.dart';
import 'package:flutter_pptx/flutter_pptx.dart';

void main() {
  runApp(DemoApp());
}

class DemoApp extends StatelessWidget {
  const DemoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo App',
      home: Scaffold(
        body: Center(
          child: Material(
            color: Colors.orangeAccent,
            child: InkWell(
              onTap: () async {
                final powerpoint = FlutterPowerPoint();

                powerpoint.addTitleAndBulletsSlide(
                  title: 'Slide Title'.toTextValue(),
                  bullets: [
                    'Bullet 1',
                    'Bullet 2',
                  ].map((e) => e.toTextValue()).toList(),
                );

                final powerpointBytes = await powerpoint.save();
                await FileSaver.instance.saveFile(
                  name: 'sample',
                  bytes: powerpointBytes,
                  mimeType: MimeType.microsoftPresentation,
                  ext: 'pptx',
                );
              },
              child: Padding(
                padding: EdgeInsets.all(32),
                child: Text('Create Powerpoint and Download'),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

file_saver: 0.2.6
flutter_pptx: 0.1.2+1

**Comment by rodydavis** [comment]
I am getting other reports about Microsoft PowerPoint showing it as corrupted.

Works fine opening in slides and keynote.

Looking into the issue to see if it is on the file format side.

**Comment by UlasAkgun** [comment]
@rodydavis Thank you very much for merging the PR for updating the dependencies for compatibility!

https://github.com/rodydavis/flutter_pptx/pull/6 

Since the PR is merged, I think we can close this issue. 

Microsoft Powerpoint corrupt file issue can probably be a part of another issue. I tried a few things to troubleshoot why the files are corrupt, yet I have been unable to find a solution yet. The files open fine on Powerpoint viewers on browsers though.

**Comment by rodydavis** [comment]
Sounds good to me! Also it has been working fine for me with keynote and slides too.

And you are welcome 🎉
